# Generated by Django 5.2.9 on 2026-01-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeMemo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo_id", models.IntegerField(unique=True)),
                ("sender_address", models.CharField(max_length=42)),
                ("name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("eth_amount", models.DecimalField(decimal_places=18, max_digits=20)),
            ],
        ),
    ]
