# Generated by Django 5.2.9 on 2026-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_coffeememo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeememo",
            name="eth_amount",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
